### ISSUE TITLE
no \sffamily/\rmfamily in template

### ISSUE THREAD

**Issue by Glottotopia** [guidovw/Glossalatex#8]
Low level commands like `\sffamily` or `\rmfamily` should be dealt with in the cls. They should not be found in the template as they will either a) confuse authors or b) (worse) suggest that it is OK for authors to use all kinds of low level commands. 

In the current template, they are found around the title, and for tabulars. For both cases, it should be possible to achieve the desired result via the cls.

**Comment by guidovw** [comment]
Sorry for being so slow to reply, but I've been rather busy over the last weeks. I've added you as a collaborator on this template, feel free to make the relevant commits. I might look at your suggestions myself later, but for the immediate future I have more pressing matters.

**Comment by guidovw** [comment]
I've now corrected this and moved these commands to the cls file
